version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: microstay-postgres
    environment:
      POSTGRES_DB: microstay
      POSTGRES_USER: microstay
      POSTGRES_PASSWORD: microstay
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.2
    container_name: microstay-keycloak
    command: ["start-dev", "--import-realm"]
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: dev-file
    ports:
      - "8081:8080"
    volumes:
      - ./infra/keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: microstay-backend
    depends_on:
      - postgres
      - keycloak
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DB_URL: jdbc:postgresql://postgres:5432/microstay
      DB_USERNAME: microstay
      DB_PASSWORD: microstay
      KEYCLOAK_ISSUER_URI: http://keycloak:8080/realms/microstay
      KEYCLOAK_JWKS_URI: http://keycloak:8080/realms/microstay/protocol/openid-connect/certs
      SERVER_PORT: 8080
      UPLOADS_DIR: /app/uploads
    ports:
      - "8080:8080"
    volumes:
      - uploads:/app/uploads

volumes:
  db_data:
  uploads:



